// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Test scope", Scope = "type", Target = "~T:MediatR.Courier.Tests.ConventionClientTests.ClientTypeTestData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.ConventionClientTests.ConventionClientMethodInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.InterfaceClientTests.SubscribedMethodInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.InterfaceClientTests.MultipleSubscribedMethodsInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.InterfaceClientTests.MultipleSubscribedAsyncMethodsInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.CourierTests.AsyncVoidActionMightCompleteInTime(System.TimeSpan)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.CourierTests.SubscribedActionInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.CourierTests.SubscribedAsyncActionInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.CourierTests.UnSubscribedActionNotInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.NamingRules", "SA1313:Parameter names should begin with lower-case letter", Justification = "Test scope", Scope = "member", Target = "~M:MediatR.Courier.Tests.CourierTests.UnSubscribedAsyncActionNotInvoked~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Test scope", Scope = "type", Target = "~T:MediatR.Courier.Tests.CourierTests.AsyncTestData")]
