trigger:
- '*'

pool:
  vmImage: 'windows-latest'
  demands: java

variables:
  buildConfiguration: "Release"

steps:

- script: dotnet restore --configuration $(buildConfiguration)
  displayName: 'Restore'

- task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'SonarCloudCourier'
    organization: kuraiandras-devops
    projectKey: 'MediatR.Courier'
    projectName: 'MediatR.Courier'
    extraProperties: |
      projectBaseDir=$(Build.SourcesDirectory)
      sonar.exclusions=**/obj/**,**/*.dll,**/*.js,**/*.ts
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
      sonar.verbose=true

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet test --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx
  displayName: 'Test'

- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator "-reports:$(Build.SourcesDirectory)/**/coverage.opencover.xml" "-targetdir:$(Build.SourcesDirectory)/CodeCoverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
  displayName: Create Code Coverage Report

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'

- task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
  continueOnError: false

- task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
  displayName: 'Publish Quality Gate Result'
  continueOnError: false