name: pr-ci

on:
  pull_request:
    branches:
      - master

jobs:
  pr-ci:
    name: pr-ci
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test --no-build --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: Check Analyzers
        run: dotnet format --verify-no-changes --verbosity diagnostic
