name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - name: Pack
        run: |
          dotnet pack ./MediatR.Courier --configuration Release --output ./artifacts /p:Version="${GITHUB_REF_NAME}"

      - name: Publish
        run: |
          dotnet nuget push ./artifacts/ --api-key "${{ secrets.NUGET_API_KEY }}"
