name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup Tools .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: ./build.ps1 PushToNuGet --nuget-api-key $env:NUGET_API_KEY --configuration Release --ci-build true
