name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: ./build.ps1 PushToNuGet --nuget-api-key $env:NUGET_API_KEY --configuration Release --deterministic-source-paths "true"
