name: Run CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  RunCI:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK for Sonar
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run './build.cmd RunCi'
        run: ./build.cmd RunCi
        env:
          SonarHostUrl: ${{ secrets.SONAR_HOST_URL }}
          SonarProjectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          SonarToken: ${{ secrets.SONAR_TOKEN }}
          SonarOrganization: ${{ secrets.SONAR_ORGANIZATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
